default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV['DB_NAME'] %>
  pool: <%= ENV['DB_POOL'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>


development:
  adapter: sqlite3
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  timeout: 5000

production:
  <<: *default

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000